ALTER TABLE `products`
  ADD COLUMN `gst_type` VARCHAR(191) NOT NULL DEFAULT 'GST',
  ADD COLUMN `gst_percentage` DECIMAL(5,2) NOT NULL DEFAULT 0;

ALTER TABLE `order_items`
  ADD COLUMN `gst_type` VARCHAR(191) NOT NULL DEFAULT 'GST',
  ADD COLUMN `gst_percentage` DECIMAL(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN `gst_amount` DECIMAL(12,2) NOT NULL DEFAULT 0;
